# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=100)),
                ('question_description', models.CharField(max_length=10000)),
                ('question_input_file', models.CharField(max_length=200)),
                ('question_output_file', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_status', models.CharField(max_length=50)),
                ('submission_language', models.CharField(max_length=50)),
                ('submission_time', models.FloatField(default=100.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinejudge.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinejudge.User')),
            ],
        ),
    ]
