# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 16:28
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0002_question_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(default='settings.MEDIA_ROOT/background.gif', storage=django.core.files.storage.FileSystemStorage(location=b'/home/priyansh/OJ/OnlineJudge/media'), upload_to='documents/'),
        ),
    ]
